name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your working branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/nginx-app
          git pull origin main
          chmod +x deploy.sh
          ./deploy.sh